### ISSUE TITLE
Support Kubernetes Headless Service Resolver for RingHash/MagLev consistent hashing.

### ISSUE THREAD

**Issue by alaa** [emissary-ingress/emissary#2878]
**Please describe your use case / problem.**
I have a StatefulSet which requires consistent-hashing LB to partition traffic deterministically. AFAIK, Ambassador provides only 2 kinds of Resolvers for advanced load-balancing (Endpoint and Consul) which all returns the endpoints addresses to the underlying hashing function. The problem is, the StatefulSet pods IPs might change, this will break the consistency of the partitioning.
 
**Describe the solution you'd like**
The solution for this, most likely, is to have a `Headless-Service Resolver` which returns the StatefulSet PODS CNAMEs "instead of the IPs" to the underlying hashing function (ringhash or maglev).

**Additional context**
- This issue was discussed at Envoy and a PR is merged addressing it. 
https://github.com/envoyproxy/envoy/pull/10233

- Envoy has an option `use_hostname_for_hashing` to consistently hash the upstream hostname.
https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cluster.proto

- Kubernetes StatefulSet: (Using Stable Network Identities).
https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#using-stable-network-identities

**Comment by kflynn** [comment]
Sounds like an excellent idea. 🙂 Ambassador 1.6 includes an Envoy that has support for this, though Ambassador itself can't yet configure it, so we'll have to look at where it can go on the roadmap. (PRs, as always, welcome.)

**Comment by kflynn** [comment]
For anyone who's thinking of tackling this: the challenge here is that it's a change to the discovery mechanisms built into Ambassador, since we don't currently watch for `StatefulSets`. So you'll need to:

1. Create a new `KubernetesStatefulSetResolver` type (not hard, it'll look like a `KubernetesServiceResolver` with a different `kind`)
2. Teach `watt` to watch `StatefulSet`s (not hard, either add it to the static list in `entrypoint.sh` or have the `watch_hook` return it as a K8s watch if any `KubernetesStatefulSetResolver`s are in play, with the second being preferred)
3. Teach the `ResourceFetcher` chain to use information in the `StatefulSet`s to enumerate the endpoints of a `Service`s that are using a `KubernetesStatefulSetResolver` (unknown difficulty; this happens very far down in the system and there are some complexities lurking in there)
4. Teach load balancers using a `KubernetesStatefulSetResolver` to use hostnames rather than IP address (shouldn't be hard, if #3 is done correctly)
5. MAKE SURE THERE ARE TESTS FOR THIS (probably annoying, but we have load balancer tests for examples)

Definitely doable, but not the most trivial thing to tackle.
