### ISSUE TITLE
Unable to access Edge Policy Console through port-forwarding

### ISSUE THREAD

**Issue by vsimon** [emissary-ingress/emissary#2978]
**To Reproduce**

1. Installed the latest helm-chart from datawire/ambassador
2. kubectl port-forward -n ambassador deploy/ambassador 8877
3. Access http://localhost:8877/edge_stack/ or http://localhost:8877/edge_stack/admin/ returns a 404 Not Found
(http://127.0.0.1:8877/ambassador/v0/diag/ does work)

Based off the port-forward instructions from here: https://www.getambassador.io/docs/latest/topics/running/ambassador/#diagnostics-diagnostics

**Expected behavior**
An /edge_stack/ endpoint to be accessible via port-forwarding

**Versions (please complete the following information):**
 - Ambassador: 1.7.1
 - Kubernetes environment - EKS
 - Version - 1.17

**Additional context**

**Comment by cakuros** [comment]
The Edge Policy console must be logged into via the `edgectl login` command.  This is because there is an internal JWT validation method going on behind the scenes.  Techincally speaking, the actual page is served on port 8500 on `/edge_stack_ui/edge_stack/admin/`, however this won't work regardless (it will take you to the 404 page).  The way I got this to work was to do `kubectl port-forward -n ambassador deploy/ambassador 8443` and then `edgectl login -n ambassador localhost:8443`.  In your browser this will pop up a certificate notification that it's self-signed, going through should take you to the page.

**Comment by vsimon** [comment]
Thanks for the info but I wasn't able to get past the last step in the browser on three browsers I tried.

firefox had this with no way to get past

<img width="897" alt="image" src="https://user-images.githubusercontent.com/137727/93251197-baafa280-f748-11ea-9cf4-50356a64ced7.png">

chrome 

<img width="681" alt="image" src="https://user-images.githubusercontent.com/137727/93251300-dadf6180-f748-11ea-93e8-05f4e0133654.png">

safari

<img width="612" alt="image" src="https://user-images.githubusercontent.com/137727/93251353-ecc10480-f748-11ea-8c75-1fd8fdafde51.png">

**Comment by vsimon** [comment]
```
kubectl port-forward -n ambassador deploy/ambassador 8443
edgectl login -n ambassador localhost:8443
```
still results in "Secure connection failed" pages in 1.9.0

**Comment by cindymullins-dw** [comment]
With Version 2.x the Edge Policy Console has been replaced by Ambassador Cloud, which can be accessed via [a free cloud account](https://www.getambassador.io/docs/cloud/).
