### ISSUE TITLE
Security vulnerability in github.com/dgrijalva/jwt-go-v3.2.0: CVE-2020-26160

### ISSUE THREAD

**Issue by juniorz** [emissary-ingress/emissary#3122]
**Describe the bug**

At the moment we are unable to fix this CVE in a "plugin" filter due to ABI-compatibility requirements (https://www.getambassador.io/docs/latest/topics/using/filters/plugin/).

**Expected behavior**

`/ambassador/aes-abi.txt` is updated to remove the library affected by the CVE.

**Versions (please complete the following information):**
 - Ambassador: 1.9.1

**Additional information**

```
$ docker run --rm --entrypoint=cat docker.io/datawire/aes:1.9.1 /ambassador/aes-abi.txt | grep github.com/dgrijalva/jwt-go
github.com/dgrijalva/jwt-go v3.2.0+incompatible
```

**Comment by kflynn** [comment]
@juniorz Hey, thanks for filing this! I looked over CVE-2020-26160 and `jwt-go`, and have come to two conclusions:

1. Ambassador itself is not vulnerable: we don't ever use `jwt-go`'s audience validation, because we noticed the issues the CVE cites. Instead, we use `jwt-go` for cryptography and serialization, and wrote our own code to validate audiences.

2. There is, sadly, no really _good_ way to address this CVE using `jwt-go`. The last release of `jwt-go` version 3 is 3.2.0, which has the security issue. The only more recent release is 4.0.0-preview1, which is a breaking change and has been a preview for nearly a year, which doesn't fill us with confidence. Once there is an official release, we'll upgrade to it (or, if we find a better library overall, we'll simply migrate -- suggestions welcome).

I think that the best way for you to proceed, if possible, is actually to switch to using an `External` filter, which uses network communications rather than requiring exact conformance to the way we compiled Ambassador. If that's absolutely not an option, I'd recommend sidestepping `jwt-go`'s audience validation, as we do.

Thanks!

**Comment by juniorz** [comment]
Hi @kflynn. Thank you for looking into this issue.

Regarding (1), I understand we (as consumers) are not exposed to this vulnerability through the code paths used by Ambassador. However, the ABI-compatibility requirement for "plugin" filters prevents us from completely replacing the vulnerable library. This is a problem for most vulnerability management process in place, as every plugin carries a dependency with a known CVE.

Regarding (2), we have found 3 possibilities to address this CVE:

1. Upgrade to `github.com/square/go-jose`, since `dgrijalva/jwt-go` seems to be unmaintained.
1. Upgrade to `github.com/dgrijalva/jwt-go 4.0.0-preview1`. The breaking changes you mentioned were negligible for us. I remember just having to change `jwt.StandardClaims#IssuedAt` from `int` to `jwtgo.Time`.
1. Upgrade to `github.com/form3tech-oss/jwt-go v3.2.2` which is supposed to be a fork to just address the CVE while you work on one of the other two fixes.

Given your use case of `jwt-go` (cryptography and serialization), I assume using `github.com/square/go-jose` might be the path you want to investigate.

**Comment by cindymullins-dw** [comment]
Closing as confirmed this is not an Ambassador vulnerability.
