### ISSUE TITLE
Original URL is not preserved in oauth redirect URL.

### ISSUE THREAD

**Issue by masingh-19** [emissary-ingress/emissary#3372]
**Describe the bug**
After user authentication using oauth2, the ambassador redirect URL does not preserved the original URL. Portion of the URL is truncated.   

**To Reproduce**
1. Setup oauth2 filter
2. Invoke page with the url with passing additional parameter. Example here is : https://azdeploy.bdns.dev.in/MyApp1/app/#test/tcomp/infoPage?oid=VR%3Acom.change.ChangeRequest2%3A196141&&u8=1
3.Redirect to IdP for authentication. 
4. After  authentication, check the ambassador URL redirect. The portion - "test/tcomp/infoPage?oid=VR%3Acom.change.ChangeRequest2%3A196141&&u8=1" is not in the redirect URL.
5. 

**Expected behavior**
Expected that redirect url should the have original page url 

**Versions (please complete the following information):**
 - Ambassador: 1.13
 - Kubernetes environment: AKS
 - Version : 1.18

**Additional context**

**Comment by cindymullins-dw** [comment]
Answered by @selenaanguyenn: We were able to replicate this issue which has to do with how URLs work. When a fragment ("#") is used in a URL, the part of the URL after the fragment, the fragment identifier, is not sent in the HTTP request message. This is because the fragment identifier is only used by the client or browser. Because the fragment identifier is never sent in the request, Ambassador and the OAuth 2.0 Filter never know the fragment identifier, which is why the Filter redirects to a truncated version of the original URL. This truncated version is the part of the URL before the fragment. This URL behavior should be what you are experiencing since you are seeing this pattern with all URLs with "#".

Because this is the nature of URL fragment identifiers, this is not something that is changeable by Ambassador. If you were to try a workaround such as injecting the fragment identifier into a header before sending the request, that would have to be done on the client or browser side. Instead of going through that, though, we would recommend that you adapt a workflow where the user has to be logged in before accessing any URLs with fragment identifiers or anchor links. This would prevent URL truncations after SSO and OAuth 2.0.
