### ISSUE TITLE
Ambassador's k8s ingress-controller to act as an api gateway

### ISSUE THREAD

**Issue by shahamit** [emissary-ingress/emissary#3736]
I have a couple of queries about ambassador's k8s ingress-controller to act as an api gateway

1. Does ambassador provide a way to encrypt api responses and decrypt api requests centrally so that every microservices doesn't have to do it?
2. Apart from having a circuit breaker capability, is it possible to queue api requests when the backend services are under load?

Thanks.

**Comment by cindymullins-dw** [comment]
Yes, you can encrypt api responses and decrypt api requests with [TLS termination](https://www.getambassador.io/docs/emissary/latest/howtos/tls-termination) and [origination](https://www.getambassador.io/docs/emissary/latest/topics/running/tls/origination), on your Mappings, so that every response coming in to Ambassador will get unencrypted and then re-encrypted before it goes to the upstream.

Please see [max_pending_requests](https://www.getambassador.io/docs/edge-stack/latest/topics/using/circuit-breakers#circuit-breaker-configuration): that will set max number of requests while waiting for connection.  Also, you may be able to use [automatic retries](https://www.getambassador.io/docs/edge-stack/latest/topics/using/retries#automatic-retries) to get the behavior you need.
