### ISSUE TITLE
Relation between Emissary Ingress and Redis

### ISSUE THREAD

**Issue by TeHSiGGi** [emissary-ingress/emissary#3931]
Hello,

while looking into the Ambassador Edge Stack and the Emissarry Ingress in particular, I came across documentation that statet the AES using Redis https://www.getambassador.io/docs/edge-stack/latest/topics/running/aes-redis/#edge-stack-and-redis or https://www.getambassador.io/docs/edge-stack/latest/topics/running/aes-extensions/#redis.

Meanwhile I did not find exact references, how Redis would affect the performance or if Redis is a mandatory requirement.

Is there a point of documentation that you could point me, when Redis is required and for what exactly it is used?
I am especially interested in the OSS version and its relation to Redis.

Looking forward to answers, any help is much appreciated!

**Comment by cindymullins-dw** [comment]
Redis is used with Edge Stack to store license information, for rate limiting, and short-lived [authentication credentials](https://www.getambassador.io/docs/edge-stack/latest/topics/using/filters/oauth2/#redis).  It is optional, and is meant at least in part to improve performance.  For example, the JWT filter will cache responses from the jwksURI in Redis so that Ambassador does not need to grab them every time.  However you don't necessarily need to deploy Redis or use the one that comes with Edge Stack.  Many users user their own Redis instead.
