### ISSUE TITLE
Add support for external-dns to Emissary v2

### ISSUE THREAD

**Issue by egeland** [emissary-ingress/emissary#3947]
We use [external-dns](https://github.com/kubernetes-sigs/external-dns) to manage the DNS entries for our Hosts, which works beautifully in the v1.x series of Emissary.
There appears to not be this support in v2.x, meaning we can't upgrade to v2. 😱

Please add support for external-dns to v2 of Emissary, in the `Host` object as per v1 would be ideal.
v1 does this via the `external-dns.ambassador-service` annotation on the `Host` object

---
Relates to https://github.com/emissary-ingress/emissary/issues/1057 somewhat, I guess? 

Some mention of this support in the docs would be good too - even a search on the v1 docs site brings no results.. you need to deep dive (into [code](https://github.com/kubernetes-sigs/external-dns/blob/master/source/ambassador_host.go), or the Slack community) to even know about it at all... 😓

**Comment by vjdhama** [comment]
@egeland I was also frustrated about this when I upgraded to `2.x` and tried to understand how the `external-dns` support worked in v1 and not in v2.

Correct me if I am wrong, on the emissary's side there is just `Host` CRD annotation that needs to be added. The rest of the work happens on `external-dns`.

I think the best approach would be to implement support via a new source for the Emissary Ingress's `Host` CRD in `external-dns`. The [code](https://github.com/kubernetes-sigs/external-dns/blob/master/source/ambassador_host.go#L45) would be pretty similar to the Ambassador Host CRD source.

@kflynn WDYT?

I would be willing to take a stab at this if this sounds fine in `external-dns`.

**Comment by egeland** [comment]
I agree, I think most of the work would need to happen on `external-dns`. If you have an opportunity to submit it there, you'll be a hero to many! :wink:

**Comment by kflynn** [comment]
Hey all -- Emissary-ingress 2.1 is out, and `external-dns` worked with 2.1 in our testing. Let us know what you find!

**Comment by rkrzewski** [comment]
Looking at the https://github.com/kubernetes-sigs/external-dns/blob/master/source/ambassador_host.go it seems that it should work with Emissary because `getambassador.io/v2` API version and `Host` kind lines up.
It seems that it's necessary to add `external-dns.ambassador-service=emissary-ingress/emissary` annotation to every `Host` that `external-dns` should manage (assuming default Emissary LB service location). Do I get this right @egeland?

@kflynn maybe you can share what you needed to do to get `external-dns` working with Emissary Ingress 2.1?

**Comment by khussey** [comment]
Support for ExternalDNS is documented at https://www.getambassador.io/docs/emissary/latest/howtos/external-dns/.
