### ISSUE TITLE
Nginx proxy_redirect equivalent

### ISSUE THREAD

**Issue by Arttii** [emissary-ingress/emissary#4158]
I was wondering if emissary has an analogue for the nginx `proxy_redirect` directive? Or is there a way to achieve this?

**Comment by AliceProxy** [comment]
Hi @Arttii 

I'm closing this issue since the issues section of Emissary Ingress is only for bug reports / feature requests and not for general questions. I would recommend posting your question in the [Ambassador Labs Community Slack channel](https://a8r.io/slack) where other users and Ambassador employees can help you confirm if the behavior that you need is supported or not in the #emissary channel.

If you discover or are informed that the feature you need is not currently supported by Emissary Ingress then please re-create your issue by following the feature request template. 

Thank you.
