### ISSUE TITLE
Cert-Manager 1.8 support?

### ISSUE THREAD

**Issue by robd003** [emissary-ingress/emissary#4344]
Just wondering, does emissary-ingress support the latest version of cert-manager since they changed their API endpoints in the 1.7 - 1.8 releases?

**Comment by ghostsquad** [comment]
I was also curious about this, specifically for the cert generated by `apiext`. 

https://github.com/emissary-ingress/emissary/blob/bdf22367b999a79965be248480aeca49c5ee2bca/cmd/apiext/ca.go#L34

I feel like the code be cleaner if `apiext` _required_ a cert (generated by cert-manager) instead of generating it itself.

**Comment by marianafranco** [comment]
+1 Could we have an option to pass a certificate to `apiext`?

I'm also concerned about the CA expiration: https://github.com/emissary-ingress/emissary/issues/4442
