### ISSUE TITLE
Ambassador helm chart deploy fails on EKS 1.22 cluster as it needs api_version v1 for CRDs

### ISSUE THREAD

**Issue by rootrahulagr** [emissary-ingress/emissary#4657]
I am trying to install/upgrade ambassador on EKS 1.22 but it fails with following error since support for api_version v1beta1 has been deprecated in EKS 1.22 :

Error: release ambassador failed: CustomResourceDefinition.apiextensions.k8s.io "kubernetesserviceresolvers.getambassador.io" is invalid: spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required

I have been trying to find yaml manifest for Ambassador CRDs with api_version as v1 in datawire/ambassador-chart repo but even the master branch has v1beta1. Eg.
https://github.com/datawire/ambassador-chart/blob/master/crds/getambassador.io_consulresolvers.yaml

I had created this issue in datawire/ambassador-chart repo - https://github.com/datawire/ambassador-chart/issues/193

Later I realized that datawire/ambassador-chart repo has been moved to emissary-ingress/emissary repo. In this repo, I couldn't find any CRD manifest though.

Could someone please point me to manifest for CRDs with api_version as v1 as it's blocking our upgrade?

**Comment by cindymullins-dw** [comment]
Hi @rootrahulagr , the v1 CRDs are deprecated so we encourage you to upgrade to v2.  What version of Ambassador are you currently trying to install?  The CRDs can be applied via yaml for whichever version you need but are not available via the Helm chart because Helm does not technically support CRDs.

**Comment by rootrahulagr** [comment]
Hi @cindymullins-dw , thanks a ton for your reply. However, I am a bit confused with your statement. You said v1 CRDs are deprecated but kubernetes document says that they have deprecated v1beta1 and suggesting to upgrade to v1 CRD.
Please see this link here -

https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22

here is an example statement for one of the APIs -
"The [apiextensions.k8s.io/v1beta1](http://apiextensions.k8s.io/v1beta1) API version of CustomResourceDefinition is no longer served as of v1.22.
Migrate manifests and API clients to use the [apiextensions.k8s.io/v1](http://apiextensions.k8s.io/v1) API version, available since v1.16."

This is the reason I am trying to find manifest for CRDs with apiversion v1.
As per my research, it looks like v1 version is supported only with emissary-ingress(https://app.getambassador.io/yaml/emissary/3.3.0/emissary-crds.yaml)) and not with ambassador as its on v1beta1 (https://github.com/datawire/ambassador-chart/tree/master/crds).)

And even on 1.14.4 , CRD API version is v1beta1, so it will still fail on EKS 1.22 -
apiVersion: [apiextensions.k8s.io/v1beta1](http://apiextensions.k8s.io/v1beta1)
https://github.com/emissary-ingress/emissary/blob/v1.14.4/charts/ambassador/crds/getambassador.io_authservices.yaml

Please advise if above understanding is correct. If its' correct, then I think the only solution we have is to migrate from ambassador to emissary-ingress which would be addition effort/testing since amissary-ingress deployment needs addition resource configuration like 'host', mapping etc.. which were not there with ambassador.

Regarding your question about what version of helm I am trying to install -
I don't have any specific version requirement for ambassador, any version would do, that supports CRD api_version 'v1' since it's blocking our eks upgrade to v1.22.
I am pretty sure that we are using very old version of ambassador though. This is what our chart.yaml looks like -

apiVersion: v1
appVersion: 0.72.0
description: A Helm chart for Datawire Ambassador
name: ambassador
sources:
- https://github.com/datawire/ambassador
version: 0.1.1

**Comment by cindymullins-dw** [comment]
Hi @rootrahulagr, sorry for the confusion.  When I mentioned v1 CRDs I meant Emissary’s CRDs.  Typically, when users are updating an older version of Emissary (Ambassador) we like to have them first upgrade to 1.14.4 (the last v1 version) first.  From there, we recommend doing a side-by-side install of Emissary 2.3 (for example), set up your Listeners  and get things up and running before dropping off of 1.14.4.
However in your case I don’t think that will be possible because you’ve already upgraded to EKS 1.22.  Unfortunately Emissary 1.14 won’t work with EKS 1.22.  Here’s [a blog by our Engineering VP](https://blog.getambassador.io/ambassador-edge-stack-1-y-series-and-kubernetes-1-22-what-you-need-to-know-f2817b2b409e) that explains that in more detail, but the upshot is that you’ll need to upgrade to Emissary 2.x now, [preferably 2.4](https://www.getambassador.io/docs/emissary/2.4/tutorials/getting-started/).  For Emissary 2.x you’ll need to be using v2 resources, [as noted here.](https://www.getambassador.io/docs/emissary/latest/topics/install/upgrade/yaml/emissary-1.14/emissary-2.4/#side-by-side-migration-steps)

**Comment by rootrahulagr** [comment]
@cindymullins-dw, Thanks a lot for clarification. It makes more sense now. 

I have a few more questions here, please help to answer if you don't mind -

1) Can we directly install emissary-ingress 3.3.0 instead of 2.4 ?

2) I have been trying to figure out which one to use among emissary-ingress and ambassador edge stack. It sounds like both are same except some additional features provided with edge stack with some cost involved. Pls advise.

3) Understanding is, only 'mapping' resource (mapping.yaml) needs to be created corresponding to each microservice. 'host' and 'listener' resources will be one and common for all microservices. Please confirm.


Many Thanks!

**Comment by rootrahulagr** [comment]
Sorry for so many questions. I also noticed that CRD menifests are missing in the repo. Not sure why.

https://github.com/emissary-ingress/emissary/tree/v3.3.0/charts/emissary-ingress/templates

**Comment by cindymullins-dw** [comment]
1.) We've [outlined migration paths here](https://www.getambassador.io/docs/emissary/latest/topics/install/migration-matrix) that we've tested.  The jump from 1.x to 2.x is a significant change that will require some config adjustments.  The jump from 2.x to 3.x is much more straightforward with no need to install side by side.  Emissary is the open source version, whereas Edge Stack is licensed.  Here's[ a comparison chart of features](https://www.getambassador.io/products/edge-stack-vs-emissary-ingress).  3.) Yes, that's correct. 
 If you want to use a special port other than 80/443 you'd need to define a Listener for that as well.  
Lastly, CRDs have to be installed manually, with [these commands for example](https://www.getambassador.io/docs/emissary/2.2/tutorials/getting-started).  Helm doesn't officially support CRDs so they are not in the chart.
