### ISSUE TITLE
How to use feature on ssl-passthrough in emissary

### ISSUE THREAD

**Issue by mohania17** [emissary-ingress/emissary#4770]
**Describe the bug**
How to use feature on ssl-passthrough in emissary

**To Reproduce**
 I am not sure how to use ssl passthrough in emissary? In one the issue I can see that TCPMapping can be used but I dont know how to use it and it didnt worked for me. please help me resolving the issue How to use feature on ssl-passthrough in emissary

**Expected behavior**
SSL passthrough must work

**Versions (please complete the following information):**
 - Ambassador: [e.g. 0.32.1]
 - Kubernetes environment [e.g. Minikube, bare metal, Google Kubernetes Engine]
 - Version [e.g. 1.8.1]

**Additional context**
**Describe the bug**

**To Reproduce**
1. Go to '...'I am not  sure how to use ssl passthrough in emissary? In one the issue I can see that TCPMapping can be used but I dont know how to use it and it didnt worked for me. please help me resolving the issue

**Expected behavior**

**Versions (please complete the following information):**
 - Ambassador: [e.g. 0.32.1]
 - Kubernetes environment [e.g. Minikube, bare metal, Google Kubernetes Engine]
 - Version [e.g. 1.8.1]

**Additional context**

**Comment by cindymullins-dw** [comment]
@mohania17 , you can do this with [a TCP mapping (https://www.getambassador.io/docs/emissary/latest/topics/using/tcpmappings#tcpmapping-resources).  For this purpose, you can consider TLS and SSL as equivalents.  Where our docs explain how to [not terminate TLS](https://www.getambassador.io/docs/emissary/latest/topics/using/tcpmappings#tcpmapping-and-tls) with Emissary - those steps would be the equivalent of allowing SSL-passthrough.  Please also check the notes there about the [Listener and TLS termination](https://www.getambassador.io/docs/emissary/latest/topics/using/tcpmappings#downstream-configuration) because these need to be in agreement to work.
