### ISSUE TITLE
Support bypass_auth flag in Ingress resources

### ISSUE THREAD

**Issue by arturodilecce** [emissary-ingress/emissary#5034]
Atm is not possible to use the `bypass_auth` flag when using Emissary with Ingress resources. 

With custom annotations in the namespace of `getambassador.io` would be possible to specify additional configurations that the Mapping resources provide, making easier the leverage of `Ingress` resources. In this case for example the solution would be to allow the optional annotation `getambassador.io/bypass-auth: (false|true)`.

**Comment by arturodilecce** [comment]
@alexgervais - sorry to ping you directly, who can I ask for more opinions on this issue and the related PR?

**Comment by LanceEa** [comment]
@arturodilecce - We talked it over in the Maintainers Dev Meeting today. We are not open to accepting this feature request at this time because we do not want introduce any new features for Ingress support. Our core configuration language is where feature development can take place and as Gateway-API matures we would want to focus efforts there.

Thanks for the consideration!

**Comment by arturodilecce** [comment]
@LanceEa - I understand the focus on the support of the GatewayAPI but at the same time I find the Ingress support very limited and I think that having a set of annotations able to extend it could be very useful for pushing the people to migrate to using Emissary-Ingress. Worth to say that all of the features can be implemented simply by fixing the Ingress -> Mapping translation and can be restricted to a limited part of the code without affecting the whole codebase.
