### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by MichaelGrobman** [emissary-ingress/emissary#5077]
**Describe the bug**
shut down with error error: PANIC: reflect: reflect.Value.Set using value obtained using unexported field" func=github.com/emissary-ingress/emissary/v3/pkg/busy.Main file="/go/pkg/busy/busy.go:87

It just happen with no apparent reason, was working without issues for 8 days.

**Versions (please complete the following information):**
 - Emissary-ingress: 8.6.0
 - GKE: 1.26.2.gke.1000

**Additional context**
[emissary-ingress-74d796f6f-zk9mf.log](https://github.com/emissary-ingress/emissary/files/11614180/emissary-ingress-74d796f6f-zk9mf.log)

**Comment by cindymullins-dw** [comment]
@MichaelGrobman, is it possible you have a deprecated mapping or annotation?  That would be odd since you note it has been working for you, but there's [a similar error here](https://github.com/emissary-ingress/emissary/issues/4783) when v1 annotations are still in use somewhere in your deployment.

**Comment by MichaelGrobman** [comment]
@cindymullins-dw Yes, we do have "apiVersion: ambassador/v1" defined in the yaml's,
for example:
```
  apiVersion: ambassador/v1
      kind: Mapping
      name: noname
      prefix: /
      rewrite: ""
      service: service:3000
      host: x.com
      timeout_ms: 5000
      connect_timeout_ms: 5000
```

as we are migrating to a new cluster (from GKE 1.21 to 1.26) this system was last updated 3 years ago, which is also using a VERY old ambassador ingress version (0.86) iirc,

I am wondering if it is possible to update to the new API "getambassador.io/v3alpha1" and keep the same format as the example above.

**Comment by cindymullins-dw** [comment]
Hi @MichaelGrobman , for now I believe you can still use annotations but we recommend updating your resources to CRDs.  I'd suggest reading the notes on [Major changes with 2.x](https://www.getambassador.io/docs/emissary/latest/about/changes-2.x) and [with 3.x ](https://www.getambassador.io/docs/emissary/latest/about/changes-3.y) because there are some significant changes compared to the earlier versions.  We recommend upgrading to 2.5 first (that's the big jump) and then to 3.6, and we have [migration matrix ](https://www.getambassador.io/docs/emissary/latest/topics/install/migration-matrix)for that.

**Comment by cindymullins-dw** [comment]
Closing this issue - please let us know if any other questions.
