### ISSUE TITLE
Ability to configure Emissary to route to pods in the same Availability Zone if possible

### ISSUE THREAD

**Issue by jfiore-im** [emissary-ingress/emissary#5779]
**Please describe your use case / problem.**
Is it possible with Emissary to route requests to pods located in the same Availability Zone as the Emissary pod handling the traffic?
We are using `KubernetesEndpointResolver` which as far as I can tell has no configuration.

We would like to reduce the cross-AZ traffic to reduce costs.

**Describe the solution you'd like**
A way to configure Emissary (or the `KubernetesEndpointResolver` to prefer to use Pods for a given service that are within the same AZ as the Emissary pod handling the request).

**Describe alternatives you've considered**
I looked through the Emissary documentation and didn't find anything to this effect.
https://emissary-ingress.dev/docs/3.8/topics/using/mappings/
https://emissary-ingress.dev/docs/3.8/howtos/route/
https://emissary-ingress.dev/docs/3.8/topics/running/resolvers/#the-kubernetes-endpoint-resolver
https://emissary-ingress.dev/docs/3.8/topics/running/load-balancer/
I didn't find anything that looked like it would solve this in the LoadBalancer policy

**Additional context**
We are using Emissary `3.8.2`

**Comment by kflynn** [comment]
Emissary can't do this natively. 🙁 The endpoint resolver is definitely where to start, but if you're after reducing cross-AZ traffic you're probably better off doing that [in the service mesh](https://buoyant.io/download/high-availability-zonal-load-balancing).

(Full disclosure: I'm employed by Buoyant. I think Linkerd's HAZL is _extremely_ cool, but on the other hand, if you're interested in adding this to Emissary, I'd be totally down to support you! though I'd strongly suggest you start with the dev/v4` branch rather than Emissary 3.)

**Comment by jfiore-im** [comment]
Thanks @kflynn 
After some further research, I think I may be able to get what I need with Topology Aware Routing in newer versions of K8S. 
Just gotta do those upgrades now.
